name: Build and Publish Release

on:
  release:
    types: [released, edited]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-and-publish:
    # Name the Job
    name: Build and Publish Release
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.20.2]

    steps:
      # jq is needed for the package-bump-version script
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      - name: Checkout Codebase
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --production=false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      - name: Run Build Script
        run: yarn build
      - name: Run Test Framework
        run: yarn test
